services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs

  silly_tavern_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "52006:52006"
    depends_on:
      - redis
