server:
  port: 52006
  error:
    include-message: always

spring:
  codec:
    max-in-memory-size: 20MB
  profiles:
    active: dev

wen-xiao-bai:
  user-id: 128824
  tokens:
    - Braser your wen xiao bai tokens

deepseek:
  tokens:
    - Bearer your deepseek token


