server:
  port: 52006
  error:
    include-message: always

spring:
  codec:
    max-in-memory-size: 20MB

WenXiaoBai:
  userId: 128824
  tokens:
    - Braser ksajdkljwalkjddklsahdklwadkl.sadjkalwjdklsad.xcoajskdjwkla

