server:
  port: 52006
  error:
    include-message: always

spring:
  codec:
    max-in-memory-size: 20MB
#  profiles:
#    active: dev
  data:
    redis:
      host: redis
      port: 6379

#wen-xiao-bai:
#  user-id: 128824
#  tokens:
#    - Bearer your wen xiao bai tokens

deepseek:
  tokens:
    - Bearer your deepseek token
gemini:
  Apis:
    - your gemini API
    - your gemini API

debug: true

